#!/bin/bash -l
# Created on 06/14/2021 by Dunyu Liu (dliu@ig.utexas.edu)
# Change ml intel to /19.1.1. No other changes.

echo "Loading modules for CESM_postprocessing tool ..."
echo "Exporting pathes for HDF5 ..."

#ml unload xalt
ml intel/18.0.2
ml python2
ml ncl_ncarg
ml nco
ml hdf5
ml netcdf
ml udunits 

ml

export LIBRARY_PATH=$TACC_NETCDF_LIB:$TACC_HDF5_LIB:$LIBRARY_PATH
export C_INCLUDE_PATH=$TACC_NETCDF_INC:$TACC_HDF5_INC
